name: CI Pipeline

on:
  pull_request:
    branches: ['master', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # required for Sonar

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      # 3. Install dependencies (NPM)
      - name: Install Dependencies
        run: npm install

      # 4. Build project
      - name: Build
        run: npm run build

      # 5. SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@f099b441665cb71b0414100cfaf6d835492cee5f
        with:
          args: >
            -Dsonar.projectKey=basu1312_React_portfolio
            -Dsonar.organization=basu1312
            -Dsonar.sources=src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      # 6. Sonar Quality Gate (fail PR if failed)
      - name: Sonar Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 7. Upload build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist
